//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UV3Socket_Test.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PWOPTIONS_DIALOG            102
#define IDS_PROPSHT_CAPTION             103
#define IDR_MAINFRAME                   128
#define IDD_SHEET_1                     129
#define IDD_SHEET_2                     130
#define IDD_SHEET_3                     131
#define IDD_IDENTIFY                    132
#define IDD_MAKE                        133
#define IDD_DEBUG                       134
#define IDD_ENUMVTR                     134
#define IDD_TARGMESS                    135
#define IDD_TARGINFO                    137
#define IDD_RTA                         138
#define IDD_BRKDLG                      139
#define IDD_PRJOPT                      141
#define IDC_TREE1                       1000
#define IDC_S_COORDINATES               1001
#define IDC_TREE2                       1002
#define IDC_EDIT1                       1004
#define IDC_ITEXT                       1004
#define IDC_BRKEXPR                     1004
#define IDC_BUTTON1                     1005
#define IDC_REFRESH                     1005
#define IDC_SENDWHOIS                   1005
#define IDC_SENDBUILD                   1005
#define IDC_STARTDEBUG                  1005
#define IDC_MSGTOTARG                   1005
#define IDC_GETTARGINFO                 1005
#define IDC_BUTTONCLEARWINDOW           1005
#define IDC_BRKCREATE                   1005
#define IDC_GNAME                       1005
#define IDC_RADIO1                      1006
#define IDC_STOPTDEBUG                  1006
#define IDC_FNAME                       1006
#define IDC_ACTFILES                    1006
#define IDC_RADIO2                      1007
#define IDC_STARTEXEC                   1007
#define IDC_BPDISABLE                   1007
#define IDC_OPTSTR                      1007
#define IDC_PROGRESS1                   1008
#define IDC_STOPEXEC                    1008
#define IDC_BPKILL                      1008
#define IDC_BPDISABLE2                  1008
#define IDC_OPTWRITE                    1008
#define IDC_LIST1                       1009
#define IDC_STEPOVER                    1009
#define IDC_LISTRXRTA                   1009
#define IDC_LISTOUT                     1009
#define IDC_BPENABLE                    1009
#define IDC_COMBO1                      1010
#define IDC_STEPINTO                    1010
#define IDC_TMCHA                       1010
#define IDC_RECEIVED                    1011
#define IDC_STEPOUT                     1011
#define IDC_SENDREBUILD                 1012
#define IDC_STEPINSTR                   1012
#define IDC_SENDSTOPBUILD               1013
#define IDC_ISRUNNING                   1013
#define IDC_SETFILEGROUP                1014
#define IDC_CYC_TSTAMP                  1014
#define IDC_SETOPTIONS                  1015
#define IDC_SETINTERVAL                 1015
#define IDC_EXECUNTIL                   1016
#define IDC_CLEANPRJ                    1016
#define IDC_EDUNTIL                     1017
#define IDC_GETMEMADR                   1018
#define IDC_RESET                       1019
#define IDC_SHOWMA                      1020
#define IDC_SETBP                       1021
#define IDC_CLRBP                       1022
#define IDC_SETBPEXP                    1023
#define IDC_CLRBPEXP                    1024
#define IDC_READREG                     1025
#define IDC_REGNAME                     1026
#define IDC_REGVAL                      1027
#define IDC_WRITEREG                    1028
#define IDC_READMEM                     1029
#define IDC_WRITEMEM                    1030
#define IDC_WHICHDOC                    1030
#define IDC_DECMEMA                     1031
#define IDC_GETPRJFILE                  1032
#define IDC_CLRBPALL                    1032
#define IDC_FILESEQ                     1033
#define IDC_GETVERS                     1033
#define IDC_EDENID                      1034
#define IDC_VTRNAME                     1035
#define IDC_GETMEMADR2                  1036
#define IDC_IDENUM                      1036
#define IDC_GETVTR                      1037
#define IDC_MAPTOFL                     1038
#define IDC_MAPTOCODE                   1039
#define IDC_SHOWCODE                    1039
#define IDC_VTRVAL                      1040
#define IDC_SETVTR                      1041
#define IDC_SEND                        1049
#define IDC_RECEIVE                     1050
#define IDC_SERSEND_D                   1052
#define IDC_GETSERO                     1054
#define IDC_EDGROUP                     1055
#define IDC_ADDGRP                      1056
#define IDC_DELGROUP                    1057
#define IDC_EDFILENAME                  1058
#define IDC_ADDFILE                     1059
#define IDC_DELFILE                     1060
#define IDC_SHOWRAW                     1060
#define IDC_BUTTONRTA                   1061
#define IDC_RECEIVEDRTA                 1062
#define IDC_CHECKCUST1                  1063
#define IDC_CHECKCUST2                  1064
#define IDC_CHECKTASKSWITCH             1065
#define IDC_CHECKCUST3                  1066
#define IDC_CLEARLOG                    1066
#define IDC_CHECKCUST4                  1067
#define IDC_FLASHDOWNLOAD               1067
#define IDC_CHECKCUST5                  1068
#define IDC_BUTTON_HIDE                 1068
#define IDC_CHECKCUST6                  1069
#define IDC_BUTTON_SHOW                 1069
#define IDC_BREAKPOINTS                 1069
#define IDC_CHECKCUST7                  1070
#define IDC_BUTTON_MINIMIZE             1070
#define IDC_BRKTYPE                     1070
#define IDC_CHECKCUST8                  1071
#define IDC_BUTTON_MAXIMIZE             1071
#define IDC_CHECKCUST9                  1072
#define IDC_BUTTON_UILOCK               1072
#define IDC_CHECKCUST10                 1073
#define IDC_BUTTON_UIUNLOCK             1073
#define IDC_CHECKCUST11                 1074
#define IDC_BUTTON_EXIT_UVISION         1074
#define IDC_BRKCOUNT                    1074
#define IDC_CHECKCUST12                 1075
#define IDC_BUTTON_RESTORE2             1075
#define IDC_BUTTON_RESTORE              1075
#define IDC_BRKCMD                      1075
#define IDC_CHECKCUST13                 1076
#define IDC_ACCSIZE                     1076
#define IDC_CHECKCUST14                 1077
#define IDC_CHECKCUST15                 1078
#define IDC_CHECKCUST16                 1079
#define IDC_BPLIST                      1080
#define IDC_PRJOPTIONS                  1081
#define IDC_ENUMFILES                   1081
#define IDC_TNAME                       1082
#define IDC_PRJOPTIONS2                 1082
#define IDC_JOBTYPE                     1083
#define IDC_ENUMGROUPS                  1083
#define IDC_OPTREAD                     1084
#define IDC_BUTTON_TEST1                1085
#define IDC_BUTTON_TEST2                1086
#define IDC_BUTTON_TEST3                1087
#define IDC_BUTTON_TEST4                1088
#define IDC_BUTTON_TEST5                1089
#define IDC_BUTTON_TEST6                1090
#define IDC_BUTTON_TEST7                1091
#define IDC_BUTTON_TEST8                1092
#define IDC_BUTTON_TEST9                1093
#define IDC_BUTTON_TEST10               1094
#define IDC_BUTTON_TEST11               1095
#define IDC_BUTTON_USIM                 1096
#define IDC_BUTTON_UTRG                 1097
#define IDC_PROGRESS                    1098
#define IDC_CLOSEPRJ                    1099
#define IDC_PROGRESS2                   1100
#define IDC_GETEXTVERSION               1100
#define IDC_PRJREAD                     1100
#define IDC_ENUMSTACK                   1101
#define IDC_ENUMVTR                     1102
#define IDC_ENUMVTRV                    1104
#define IDS_TRACELOG_UNKNOWN_ERROR      5000
#define IDS_TRACELOG_FILTER             5001
#define IDS_TRACELOG_FILE_SAVE          5002
#define IDS_TRACELOG_FILE_SAVE_AS       5003
#define IDS_TRACELOG_FILE_OPEN_FAILED   5004
#define IDS_TRACELOG_CAPTION            5005
#define IDS_TRACELOG_DELETED_ENTRIES    5006
#define IDS_WSAEINTR                    10004
#define IDS_WSAEBADF                    10009
#define IDS_WSAEACCESS                  10013
#define IDS_WSAEFAULT                   10014
#define IDS_WSAEINVAL                   10022
#define IDS_WSAEMFILE                   10024
#define IDS_WSAEWOULDBLOCK              10035
#define IDS_WSAEINPROGRESS              10036
#define IDS_WSAEALREADY                 10037
#define IDS_WSAENOTSOCK                 10038
#define IDS_WSAEDESTADDRREQ             10039
#define IDS_WSAEMSGSIZE                 10040
#define IDS_WSAEPROTOTYPE               10041
#define IDS_WSAENOPROTOOPT              10042
#define IDS_WSAEPROTONOSUPPORT          10043
#define IDS_WSAESOCKTNOSUPPORT          10044
#define IDS_WSAEOPNOTSUPP               10045
#define IDS_WSAEPFNNOSUPPORT            10046
#define IDS_WSAEAFNOSUPPORT             10047
#define IDS_WSAEADDRINUSE               10048
#define IDS_WSAADDRNOTAVAIL             10049
#define IDS_WSAENETDOWN                 10050
#define IDS_WSAENETUNREACH              10051
#define IDS_WSAENETRESET                10052
#define IDS_WSAECONNABORTED             10053
#define IDS_WSAECONNRESET               10054
#define IDS_WSAENOBUFS                  10055
#define IDS_WSAEISCONN                  10056
#define IDS_WSAENOTCONN                 10057
#define IDS_WSAESHUTDOWN                10058
#define IDS_WSAETOOMANYREFS             10059
#define IDS_WSAETIMEDOUT                10060
#define IDS_WSAECONNREFUSED             10061
#define IDS_WSAELOOP                    10062
#define IDS_WSAENAMETOOLONG             10063
#define IDS_WSAEHOSTDOWN                10064
#define IDS_WSAEHOSTUNREACH             10065
#define IDS_WSAENOTEMPTY                10066
#define IDS_WSAEPROCLIM                 10067
#define IDS_WSAEUSERS                   10068
#define IDS_WSAEDQUOT                   10069
#define IDS_WSAESTATE                   10070
#define IDS_WSAEREMOTE                  10071
#define IDS_WSASYSNOTREADY              10091
#define IDS_WSAVERNOTSUPPORTED          10092
#define IDS_WSANOTINITIALIZED           10093
#define IDS_WSAEDISCON                  11001
#define IDS_WSAENOMORE                  11002
#define IDS_WSAECANCELLED               11003
#define IDS_WSAEINVALID_PROC_TABLE      11004
#define IDS_WSAEINVALIDPROVIDER         11005
#define IDS_WSAEPROVIDERFAILEDINIT      11006
#define IDS_WSASYSCALLFAILURE           11007
#define IDS_WSASERVICE_NOT_FOUND        11008
#define IDS_WSATYPE_NOT_FOUND           11009
#define IDS_WSA_E_NO_MORE               11010
#define IDS_WSA_E_CANCELLED             11011
#define IDS_WSAEREFUSED                 11012
#define ID_DEFCOM_DEVICE_LOG_ERR        20000
#define ID_DEFCOM_DEVICE_LOG_WRN        20001
#define ID_DEFCOM_DEVICE_LOG_MSG        20002
#define ID_DEFCOM_DEVICE_LOG_TRC        20003
#define ID_DEFCOM_DEVICE_LOG_COMMENT    20004
#define ID_DEFCOM_DEVICE_LOG_DATA_STRING 20005
#define ID_DEFCOM_DEVICE_LOG_DATA_8BIT  20006
#define ID_DEFCOM_DEVICE_LOG_DATA_16BIT 20007
#define ID_DEFCOM_DEVICE_LOG_DATA_32BIT 20008
#define ID_DEFCOM_DEVICE_LOG_DATA_64BIT 20009
#define IDM_LOGWINDOW                   32771
#define ID_EDIT_SELECTALL               32771
#define IDM_CLEAR                       32773
#define IDM_TEST_COMMENT                32774
#define IDM_TEST_ERROR                  32775
#define IDM_TEST_FORMATERROR            32776
#define IDM_TRACE_FORMATMESSAGE         32777
#define IDM_TEST_DATA                   32778
#define IDM_TEST_DATA_BINARY            32779
#define IDM_TEST_DATA_STRING            32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
